project:
  type: website

website:
  title: "Portfolio"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "[Made with Quarto](https://quarto.org/)"
  navbar:
    right:
      - text: Home
        href: index.qmd
      
format:
  html:
    backgroundcolor: "#eeffee"
    fontcolor: "black"
    linkcolor: "purple"
    mainfont: "Arial"
    fontsize: 20px
    monobackgroundcolor: "purple"
    theme: [cosmo, styles.scss]

